#!/bin/sh
#
# Sensible Daten sollen aus Dateien entfernt werden

# Pfad zu den Dateien und zum Backup-Verzeichnis
CONFIG_XML="defaults/caravanpiConfig.xml"
README_MD="defaults/README.md"
BACKUP_DIR=".git_sensible_backup"

# Backup-Funktion
backup_files() {
    cp "$1" "$BACKUP_DIR/$(basename $1).backup"
}

# Dateien vor der Bearbeitung sichern
backup_files "$CONFIG_XML"
backup_files "$README_MD"

# Funktion, um die Dateien zu bearbeiten (wie zuvor)
update_files() {
    sed -i 's/<MariaDBpasswd>[^<]*<\/MariaDBpasswd>/<MariaDBpasswd>dasGeheimePasswort<\/MariaDBpasswd>/' "$1"
    sed -i 's/<MQTTpassword>[^<]*<\/MQTTpassword>/<MQTTpassword>dasGeheimePasswort<\/MQTTpassword>/' "$1"
    sed -i 's/<MQTTbroker>[^<]*<\/MQTTbroker>/<MQTTbroker>MQTTBrokerWebAdresse<\/MQTTbroker>/' "$1"
}

# Dateien aktualisieren
update_files "$CONFIG_XML"
update_files "$README_MD"

# Fügen Sie die geänderten Dateien dem Commit hinzu
git add "$CONFIG_XML"
git add "$README_MD"

exit 0